# Assignment
* Download the "Assignment.ipynb" notebook 
* Fill in the code in the cells marked with #GRADED#
* Code cells outside of #GRADED# will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it

In [16]:
#Import necessary libraries
import pandas as pd
import numpy as np

In [27]:
### GRADED
arr = np.arange(15).reshape(3, 5)
print(arr.shape)
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (a) This is a matirx with five rows and three columns, the type of elements is integer between 0 to 14.
df1 = pd.DataFrame({'A': ['0', '5', '10'],
                    'B': ['1', '6', '11'],
                    'C': ['2', '7', '12'],
                    'D': ['3', '8', '13'],
                    'E': ['4', '9', '14']},
                     index=[0, 1, 2])
print(df1)
# (b) Determine the sum of elements in arr
df2 = np.sum(arr)
print(df2)
# (c) Determine the mean of elements in arr
df3 = np.mean(arr)
print(df3)
# (d) Create an array of the same shape as arr but filled with zeros
df4 = np.zeros((3,5))
print(df4)
# (e) Create an array of the same shape as arr but filled with ones
df5 = np.zeros([3,5])
print(df5)
# (f) Create an array of the same shape as arr but where all elements are squared values
df6 = np.square(arr)
print(df6)
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
df7 = np.matrix.transpose(arr)
print(df7)
df8 = np.dot(arr,df7)
print(df8)

(3, 5)
    A   B   C   D   E
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
105
7.0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [60]:
### GRADED
# The following piece of code creates a DataFrame 
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows
# (a) Determine the shape of the dataframe
np.shape(df)
# (b) Print out all the columns of the dataframe
print(df.ix[:,:])
# (c) Print the 3rd element of the dataframe
print(df.ix[2, :])
# (d) Find the average of 'petal_width' where species is 'virginica'
vir = df.loc[df['species'] == 'virginica']
print(np.mean(vir['petal_width']))
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
seto = df.loc[df['species'] == 'setosa']
print(max(seto['sepal_width']))
# (f): What is the average value of sepal_length
print(np.mean(df['sepal_length']))
# (g): What is the maximum value of sepal_width
print(max(df['sepal_width']))
# (h): What is the minimum value of petal_width
print(min(df['petal_width']))

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0    

/Users/hayashiyasushi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':
/Users/hayashiyasushi/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # This is added back by InteractiveShellApp.init_path()


### GRADED: Getting started on the capstone project
We will start working on our capstone project this week. For this week, the task consists of
Finding a dataset of interest.
    -You can use the links in the supplementary materials to help you find the dataset
    -This dataset should be publicly accessible and available for download
    -Should be of interest to the class
    -The goal is to be askign and answering important questions about the data
You can start with the following datasets or find your own
### Open datasets
          
* Resources for open data
  * https://data.boston.gov/
  * https://www.data.gov/
  * https://www.bls.gov/data/
  * http://www.fao.org/statistics/databases/en/
  * http://ec.europa.eu/eurostat/web/main
  * https://github.com/awesomedata/awesome-public-datasets
  * https://www.kdnuggets.com/2016/05/top-10-datasets-github.html
  * https://www.quora.com/Where-can-I-find-large-datasets-open-to-the-public
    
### Questions

* Q: Shortlist three datasets of interest
* Q: For each dataset suggest describe the data (a few sentences) and questions that can be answered using that data (a few sentences)


In [ ]:
# My three datasets of interest:
#"Raomfall in Boston": https://data.boston.gov/dataset/rainfall-data
This dataset has different classification of rainfalls in Boston, several different columns include 'year', 'season', 
'month' and 'week' could be viewed as a dimension of my research, for different season, the rainfll might be different.
Also, these data describe different location in Boston, therefore, the official departement could monitor the 
efficiency of our sewer and drain systems during storm conditions especially for more rainfall area in Boston. 
In addition, they acclaim that this information could be used to evaluate the capacity of their infrastructure
and plan proactive maintenance projects.
#"Food Price Outlook": https://catalog.data.gov/dataset/food-price-outlook
This dataset includes different types of foods price and their previous price, which could be used to do the comparison,
some food catagory such as vegetables and meat could be used to investigate the market situation of food sale industry.
Furthermore, different state has different food price, theses states had been listed in the dataset and the rank of food
price in U.S. states could be established to do the analysis of state tax or food inport and outport.
#"High School Education": https://catalog.data.gov/dataset/food-price-outlook
This dataset describes the education status of U.S. population, which mainly focus on High school education. Some people
get hired after high school according to their majors, some chose to continue the education. High school education
dataset could be helpful in researching the education model and improving the education feedback, such as participation
in rigorous curriculum;small schools of choice; career academies and career counseling.